insert into pricing_plans (
  slug,
  name,
  description,
  monthly_price,
  annual_price,
  currency_code,
  features,
  feature_heading,
  cta_label,
  cta_href,
  highlight,
  badge_label,
  button_tone,
  sort_order
) values
  (
    'free',
    'Free',
    'Perfect for individuals starting their journey.',
    0,
    0,
    'USD',
    ARRAY[
      'Real-time code suggestions',
      'Basic integration logos',
      'Single MCP server connection',
      'Up to 2 AI coding agents',
      'Vercel deployments with Pointer branding'
    ]::text[],
    'Get started today:',
    'Get Started',
    '/auth?view=signup',
    false,
    null,
    'neutral',
    1
  ),
  (
    'pro',
    'Pro',
    'Ideal for professionals.',
    20,
    16,
    'USD',
    ARRAY[
      'Enhanced real-time previews',
      'Unlimited integrations with custom logos',
      'Multiple MCP server connections',
      'Up to 10 concurrent AI coding agents',
      'Collaborative coding with team chat',
      'Advanced version control integrations',
      'Priority email and chat support'
    ]::text[],
    'Everything in Free +',
    'Join now',
    '/auth?view=signup',
    true,
    'Popular',
    'inverted',
    2
  ),
  (
    'ultra',
    'Ultra',
    'Tailored solutions for teams.',
    200,
    160,
    'USD',
    ARRAY[
      'Dedicated account support',
      'Unlimited MCP server clusters',
      'Unlimited AI coding agents',
      'Enterprise-grade security and compliance',
      'Priority deployments and SLA guarantees'
    ]::text[],
    'Everything in Pro +',
    'Talk to Sales',
    'mailto:sales@example.com',
    false,
    null,
    'secondary',
    3
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  monthly_price = excluded.monthly_price,
  annual_price = excluded.annual_price,
  currency_code = excluded.currency_code,
  features = excluded.features,
  feature_heading = excluded.feature_heading,
  cta_label = excluded.cta_label,
  cta_href = excluded.cta_href,
  highlight = excluded.highlight,
  badge_label = excluded.badge_label,
  button_tone = excluded.button_tone,
  sort_order = excluded.sort_order,
  updated_at = now();
